# Generated by Django 4.1.2 on 2022-10-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ittechnicstype',
            options={'verbose_name': 'Тип техники', 'verbose_name_plural': 'Тип техники'},
        ),
    ]
