# Generated by Django 4.1.2 on 2022-10-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_tech', '0002_alter_ittechnicstype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleorganization',
            options={'verbose_name': 'Наименование организации', 'verbose_name_plural': 'Наименование организации'},
        ),
    ]
