# Generated by Django 4.1.2 on 2022-10-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItTechnicsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Наименование Техники')),
                ('add_date', models.DateField(verbose_name='Дата постановки на учёт')),
                ('categorian', models.BooleanField(verbose_name='Категорированная')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleOrganization',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=60, verbose_name='Наименование')),
                ('description', models.CharField(max_length=60, verbose_name='Описание')),
            ],
        ),
    ]
