# Generated by Django 4.1.2 on 2022-10-13 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ittechnicsmodels',
            name='organization',
            field=models.ForeignKey(db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='technics.moduleorganization', verbose_name='Организация'),
        ),
    ]
