# Generated by Django 4.1.2 on 2022-10-20 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_tech', '0001_initial'),
        ('technics', '0003_alter_ittechnicsmodels_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ittechnicsmodels',
            options={'verbose_name': 'Технику', 'verbose_name_plural': 'Техника'},
        ),
        migrations.RemoveField(
            model_name='ittechnicsmodels',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='ittechnicsmodels',
            name='categorian',
        ),
        migrations.RemoveField(
            model_name='ittechnicsmodels',
            name='name',
        ),
        migrations.AddField(
            model_name='ittechnicsmodels',
            name='date_end',
            field=models.DateField(null=True, verbose_name='Вывод'),
        ),
        migrations.AddField(
            model_name='ittechnicsmodels',
            name='date_end_Kanoe',
            field=models.DateField(null=True, verbose_name='Окончание ПО КАНОЭ'),
        ),
        migrations.AddField(
            model_name='ittechnicsmodels',
            name='date_max',
            field=models.DurationField(null=True, verbose_name='MAX Период эксплуатации'),
        ),
        migrations.AddField(
            model_name='ittechnicsmodels',
            name='date_shutdown',
            field=models.DateField(null=True, verbose_name='Изъятие WIFI'),
        ),
        migrations.AddField(
            model_name='ittechnicsmodels',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Ввод в эксплуатацию'),
        ),
        migrations.AddField(
            model_name='ittechnicsmodels',
            name='date_start_Kanoe',
            field=models.DateField(null=True, verbose_name='Установка ПО КАНОЭ'),
        ),
        migrations.AddField(
            model_name='ittechnicsmodels',
            name='id_name',
            field=models.CharField(max_length=60, null=True, verbose_name='Инвентарный №'),
        ),
        migrations.AddField(
            model_name='ittechnicsmodels',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products_images', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='ittechnicsmodels',
            name='number_information',
            field=models.CharField(max_length=7, null=True, verbose_name='Номер СВТ'),
        ),
        migrations.AddField(
            model_name='ittechnicsmodels',
            name='type',
            field=models.ForeignKey(db_column='name', default=1, on_delete=django.db.models.deletion.CASCADE, to='list_tech.ittechnicstype', verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ittechnicsmodels',
            name='wifi_availability',
            field=models.CharField(choices=[('Отсутствует', 'Отсутствует'), ('Изъято', 'Изъято'), ('В наличии/не изымалось', 'В наличии/не изымалось')], max_length=100, null=True, verbose_name='Wifi'),
        ),
        migrations.AlterField(
            model_name='ittechnicsmodels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='ittechnicsmodels',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_tech.moduleorganization', verbose_name='В/Ч'),
        ),
        migrations.DeleteModel(
            name='ModuleOrganization',
        ),
    ]
