# Generated by Django 4.1.2 on 2022-10-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technics', '0005_alter_ittechnicsmodels_id_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ittechnicsmodels',
            name='date_end',
            field=models.DateField(null=True, verbose_name='Вывод из эксплуатации'),
        ),
    ]
