# Generated by Django 4.1.2 on 2022-10-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_tech', '0003_alter_moduleorganization_options'),
        ('technics', '0006_alter_ittechnicsmodels_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ittechnicsmodels',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='list_tech.moduleorganization', verbose_name='В/Ч'),
        ),
    ]
